Path matcher bug
PayU/api-contract-validator pull request #63
Opened 2021-03-15 15:57 UTC by manorlh

path matcher faild to match to correct schema key when the routes are:
/api/v1/sar/reports/:requestId
/api/v1/sar/reports/bulk

(in yaml)

for request to path /api/v1/sar/reports/bulk, it match /api/v1/sar/reports/:requested.

2021-03-15 16:09 UTC, manorlh commented
@kibertoad please review:)

2021-03-16 08:59 UTC, manorlh commented
I will try to do it better, to support more cases

2021-03-18 14:17 UTC, kobik requested changes
thanks @manorlh , please see my comments

2021-03-18 14:17 UTC, kobik commented on lib/helpers/schema-utils.js
>    return Object
lines 44-51 should be extracted and run once per routes, no need to sort on each call

2021-03-18 14:17 UTC, kobik commented on lib/helpers/schema-utils.js
> +      const firstResult = firstEl.split(':').map((value, index) => `${index}`).join('');
this sort doesn't take into account different positions that `:` can be, i.e

```js
> '/aaaa/:bbbb'.split(':').map((value, index) => `${index}`).join('')
'01'
> '/aaaa:/bbbb'.split(':').map((value, index) => `${index}`).join('')
'01'
```
this logic takes into account the path segment that `:` was found in and not its absolute position
```js
> '/aaaa/:bbbb'.split('/').map((seg) => seg.includes(':')).map((seg, i, arr) => seg * Math.pow(10, arr.length - i)).reduce((sum, seg) => sum + seg, 0)
10
> '/aaaa:/bbbb'.split('/').map((seg) => seg.includes(':')).map((seg, i, arr) => seg * Math.pow(10, arr.length - i)).reduce((sum, seg) => sum + seg, 0)
100
```

anyway, the weight calculation should be extracted to a function

2021-03-18 14:17 UTC, kobik commented on CHANGELOG.md
> +- a fix bug: route matcher
```md
## Fixes
* Prioritize exact path segment matching
 ```

2021-03-21 08:35 UTC, manorlh commented
@kobik Its ready for another check 
thanks

2021-03-25 09:49 UTC, kobik approved these changes

2021-03-25 10:05 UTC, merged